apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp # service.spec.selector와 일치해야함!
    spec:
      containers:
        - name: flex-signature-backend
          image: flex-signature-backend:port2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # 도커에서 열어주는 포트
          livenessProbe:
            httpGet:
              path: /health
              port: 3000 # 도커에서 열어주는 포트
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
